#!/usr/bin/env ruby

#TODO: re-abstract this base simple case!!!

# image declares container artifacts
@bootstrap = image {
  stage "bootstrap", "ubuntu:focal-20200606"

  command("USER") {
    "root"
  }

  env "DEBIAN_FRONTEND" => "noninteractive",
      "LC_ALL" => "C.UTF-8",
      "LANG" => "en_US",
      "LANGUAGE" => "en_US",
      "ACCEPT_EULA" => "y"

  apt %w{git curl apt-transport-https aptitude ca-certificates apt-utils software-properties-common docker.io build-essential libyaml-dev ruby2* libruby2* ruby-bundler rubygems-integration rake amazon-ecr-credential-helper}

  run %q{curl -s -v -Lo seabolt-1.7.4-Linux-ubuntu-18.04.deb https://github.com/neo4j-drivers/seabolt/releases/download/v1.7.4/seabolt-1.7.4-Linux-ubuntu-18.04.deb}
  run %q{dpkg -i seabolt-1.7.4-Linux-ubuntu-18.04.deb}

  #TODO: ???
  run %q{groupadd --gid 134 abc-otf}
  run %q{groupadd --gid 999 efg-nnn}
  run %q{useradd --uid 1000 --home-dir /home/app --create-home --shell /bin/bash app --groups docker,abc-otf,efg-nnn}

  run %q{mkdir -p /home/app/current}
  run %q{chown -R app /home/app}

  #TODO: workdir module
  command("WORKDIR") {
    "/home/app/current"
  }
}

@deploy = image {
  stage "deploy", @bootstrap.stage

  #TODO: user module
  command("USER") {
    "app"
  }

  command("COPY") {
    "--chown=app Gemfile /home/app/current/"
  }

  run %q{bundle config set --global path /home/app/vendor/bundle}
  run %q{bundle config set --global jobs 4}
  run %q{bundle config set --global retry 3}
  #run %q{bundle config set --local deploment true}
  #run %q{bundle config set --local without development}
  run %q{bundle install}

  #command("COPY") {
  #  "--chown=app . /home/app/current"
  #}
}
